### ISSUE TITLE
Consider using Model Composition to reduce duplication

### ISSUE THREAD

**Issue by Petermarcu** [connorjs/swapi-typespec#2]
I see many places where your spec could benefit from leveraging some of TypeSpecs model composition and templating support.

https://microsoft.github.io/typespec/language-basics/models#model-composition

For example, you could use `Is`, `Extends` or `...` to not have to duplicate this code in a bunch of your models

```
	/** The hypermedia URL of this resource. */
	url: url;

	/** The ISO 8601 date format of the time that this resource was created. */
	created: utcDateTime;

	/** The ISO 8601 date format of the time that this resource was edited. */
	edited: utcDateTime;
```

You could put all this in a Resource model and then have all your models Extend Resource, for example. :)

**Comment by connorjs** [comment]
Thank you @Petermarcu !
